src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
  

    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("post:read")
     */
    private $nsc;
    
  
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("post:read")
     */
    private $email;

    /**
     * @ORM\ManyToOne(targetEntity=Classroom::class, inversedBy="students" )
     * @ORM\JoinColumn(nullable=false)
     */
    private $Classroom;

    /**
     * @ORM\ManyToMany(targetEntity=Club::class, mappedBy="students")
     */
    private $clubs;

    public function __construct()
    {
        $this->clubs = new ArrayCollection();
    }


   

    public function getNsc(): ?string
    {
        return $this->nsc;
    }

    public function setNsc(?string $nsc): self
    {
        $this->nsc = $nsc;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->Classroom;
    }

    public function setClassroom(?Classroom $Classroom): self
    {
        $this->Classroom = $Classroom;

        return $this;
    }

    /**
     * @return Collection|Club[]
     */
    public function getClubs(): Collection
    {
        return $this->clubs;
    }

    public function addClub(Club $club): self
    {
        if (!$this->clubs->contains($club)) {
            $this->clubs[] = $club;
            $club->addStudent($this);
        }

        return $this;
    }

    public function removeClub(Club $club): self
    {
        if ($this->clubs->contains($club)) {
            $this->clubs->removeElement($club);
            $club->removeStudent($this);
        }

        return $this;
    }

}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use App\Entity\Classroom;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nsc')
            ->add('email')
            ->add('Classroom', EntityType::class, [
                'class'=>Classroom::class,
                'choice_label'=>'name',
                'multiple'=>false,

            ])
           
            ->add('save', SubmitType::class,
            ['label' => 'Valider'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Student;
use App\Form\StudentType;
use App\Entity\Classroom;
use App\Repository\StudentRepository;
use App\Repository\ClassroomRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class StudentController extends AbstractController
{
    /**
     * @Route("/student", name="student")
     */
    public function index(): Response
    {
        return $this->render('student/index.html.twig', [
            'controller_name' => 'StudentController',
        ]);
    }
    
     /**
     * @Route("/studentList", name="studentList")
     */
    public function readStudent()
    {
        $repository = $this->getDoctrine()->getRepository(Student::class);
        $students = $repository->findAll();

        return $this->render('student/read.html.twig', [
            'students' => $students,
        ]);
    }
    /**
     * @Route("/addStudent", name="addStudent")
     */
    public function addEtudiant(Request $request)
    {
        $student = new Student();     
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $student = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($student);
            $em->flush();
            return $this->redirectToRoute('studentList');
         }
    return $this->render('student/newEtudiant.html.twig', [
        'form' => $form->createView()
        
    ]);
}

      /**
     * @Route("/updateStudent/{id}", name="updateStudent")
     */

    public function updateStudent(Request $request,$id)
    {
        $em = $this->getDoctrine()->getManager();
        $student = $em->getRepository(Student::class)->find($id);
        $form = $this->createForm(StudentType::class, $student);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $em->flush();
            return $this->redirectToRoute('studentList');
        }
    
        return $this->render("Student/updateEtudiant.html.twig", [
            "form_title" => "Modifier un Etudiant",
            "form" => $form->createView(),
        ]);
      
    }
    /**
    * @Route("/deleteStudent/{id}", name="deleteStudent")
     */
public function deleteEtudiant( $id)
{
    $em = $this->getDoctrine()->getManager();
    $etudiant = $em->getRepository(Student::class)->find($id);
    $em->remove($etudiant);
    $em->flush();

    return $this->redirectToRoute("studentList");
}
 /**
    * @Route("/searchStudent", name="searchStudent")
     */
    public function searchEtudiant(Request $request )
    {

        $data = $request->get('search');
       
       $repository = $this->getDoctrine()->getRepository(Student::class);
       $students = $repository->findBy(['nsc' => $data]);
    return $this->render('student/search.html.twig', [
        'students' => $students,
     ]);
   
    }
       /**
    * @Route("/classroomStudents/{id}", name="classroomStudents")
     */
public function classroomStudents($id)
{
    $repository = $this->getDoctrine()->getRepository(Student::class);

        $students = $repository->classroomStudents($id);

        return $this->render('student/list.html.twig', [
            'students' => $students,
        ]);
}
    /**
     * @Route("/AllStudents", name="AllStudents")
     */
    public function AllStudents(Request $request, NormalizerInterface $Normalizer )
    {
        $repository = $this->getDoctrine()->getRepository(Student::class);
        $students = $repository->findAll();

        $jsonContent = $Normalizer->normalize($students, 'json',['groups'=>'post:read']);
        // return $this->render('student/allStudentJSON.html.twig', [
        //     'data'=> $jsonContent,
        //]);
        return new Response(json_encode($jsonContent));

    }

    /**
     * @Route("/addStudentJSON/new", name="addStudentJSON")
     */
    public function addStudentJSON(Request $request,NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $student = new Student();
        $student->setNsc($request->get('nsc'));
        $student->SetEmail($request->get('email'));
        $em->persist($student);
        $em->flush();
        $jsonContent = $Normalizer->normalize($student, 'json',['groups'=>'post:read']);
        return new Response(json_encode($jsonContent));;
    }

    /**
     * @Route("/updateStudentJSON/{nsc}", name="updateStudentJSON")
     */
    public function updateStudentJSON(Request $request,NormalizerInterface $Normalizer,$nsc)
    {

        $em = $this->getDoctrine()->getManager();
        $student = $em->getRepository(Student::class)->find($nsc);
        $student->setNsc($request->get('nsc'));
        $student->SetEmail($request->get('email'));
        $em->flush();
        $jsonContent = $Normalizer->normalize($student, 'json',['groups'=>'post:read']);
        return new Response("Information updated successfully".json_encode($jsonContent));;
    }
    /**
     * @Route("/deleteStudentJSON/{nsc}", name="deleteStudentJSON")
     */
    public function deleteStudentJSON(Request $request,NormalizerInterface $Normalizer,$nsc)
    {
        $em = $this->getDoctrine()->getManager();
        $student = $em->getRepository(Student::class)->find($nsc);
        $em->remove($student);
        $em->flush();
        $jsonContent = $Normalizer->normalize($student, 'json',['groups'=>'post:read']);
        return new Response("Student deleted successfully".json_encode($jsonContent));
    }
}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StudentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/hp/Desktop/yy/temp/test-me-asma/testMe/src/Controller/StudentController.php'|file_link(0) }}">src/Controller/StudentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/hp/Desktop/yy/temp/test-me-asma/testMe/templates/student/index.html.twig'|file_link(0) }}">templates/student/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/student/list.html.twig
<h1> Liste des classes </h1>

<table border ="1">
<tr>
   <th scope="row">ID</th>
    <th scope="row">Email</th>
    <th scope="row">NSC</th>
studentsss
</tr>
    {% for student in students %}
<tr>
   <td>

</td>
   <td>
{{ student.nsc }}
</td>
   <td>
{{ student.email }}
   </td>
 
</tr>
{% endfor %}

</table>
<div style="margin-left:50px;">
<a href="{{ path('classroomList') }}"> liste des Classes</a>
</div>

templates/student/newEtudiant.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h1> Ajouter un étudiant </h1>
<div class="contact">
<div class="php-email-form">
 <div class="col-md-6 form-group">
{{form(form)}}
</div>
</div>
</div>
<div class="contact">

            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="form-row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validate"></div>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validate"></div>
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div>
              </div>
              <div class="form-group">
                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validate"></div>
              </div>
              <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>

          </div>

{% endblock %}

 

templates/student/read.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h1> Liste des étudiants</h1>
<tr> 

<td> Recherche par </td>
<td> NSC</td>
<td>

<form method="get" action="{{ path('searchStudent') }}">

      
          <input type="text" name ="search">
          <button type="submit"> Recherche</button>
      
      </form>
      </td>

</tr>

<tr>
<table border ="1">

   <th scope="row">ID</th>
    <th scope="row">Classroom</th>
    <th scope="row">NSC</th>
    <th scope="row">Email</th>
     <th scope="row">Editer</th>
</tr>
    {% for student in students %}
<tr>
   <td>


   </td>
   <td>

{{ student.classroom.name }}

   </td>
   <td>

{{ student.nsc }}

   </td>
   <td>

{{ student.email }}

   </td>
<td>

<a href="{{ path('updateStudent', {'id': student.nsc}) }}"> modifier</a>

<a href="{{ path('deleteStudent', {'id': student.nsc}) }}"> supprimer</a>

   </td>

   
</tr>
{% endfor %}

</table>
<div style="margin-left:50px;"><a href="{{ path('addStudent') }}"> Ajouter Etudiant</a></div>

                </div>

  {% endblock %}

templates/student/search.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h1> Liste des étudiants </h1>
<tr> 
<td> Recherche par </td>
<td> NSC </td>
<td>
<form class="pull-right hidden" role="search" id="nav-search-form" 
method="post" action="{{ path('searchStudent') }}">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" name ="search">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default"> Recherche</button>
          </span>
        </div>
      </form>
      </td>

</tr>
<tr>
<table border ="1">

   <th scope="row">ID</th>
    <th scope="row">Classe</th>
    <th scope="row">NSC</th>
    <th scope="row">Email</th>
</tr>
    {% for student in students %}
<tr>
   <td>

{{ student.id }}

   </td>
   <td>

{{ student.classroom.name }}

   </td>
   <td>

{{ student.nsc }}

   </td>
   <td>

{{ student.email }}

   </td>
   
</tr>
{% endfor %}

</table>
{% endblock %}

templates/student/updateEtudiant.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h1> Modifier un étudiant </h1>

{{form(form)}}

{% endblock %}